#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ntool.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ntool.yang


class ns(object):
    hash = 436315975

    id = "http://com/tailf/ntool"

    uri = "http://com/tailf/ntool"

    prefix = "ntool"

    ntool_result = 401396173
    ntool_result_ = "result"
    ntool_device_type = 1723459864
    ntool_device_type_ = "device-type"
    ntool_command_list = 542126253
    ntool_command_list_ = "command-list"
    ntool_ntool_commands = 343090976
    ntool_ntool_commands_ = "ntool-commands"
    ntool_type = 2040883914
    ntool_type_ = "type"
    ntool_create_template = 2070825628
    ntool_create_template_ = "create-template"
    ntool_verify = 1552679042
    ntool_verify_ = "verify"
    actionpoint_ntool_commands_action_point = "ntool-commands-action-point"
